$(document).ready(function(){
  $('.bshare').click(function(){
    $('.social').toggle();
    $('#dark').toggle();
  });
  $('.mbshare').click(function(){
    $('.msocial').show();
  });
  $('#dark2').click(function(){
    $('.msocial').hide();
  });
});